title: Rehaan M. Bhimani
url: bhimar.github.io
baseurl: /portfolio-site
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: yellow
favicon: images/favicon.jpg
header:
  title: Rehaan M. Bhimani
  tagline: SWE @ Microsoft | MS CSE @ UW
  logo_img: images/logo.svg
  logo_img_alt: Rehaan Logo
  background_img: images/halfdome_crop.jpg
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Project Blog
      url: /blog
      style: link
    - label: Resume
      url: /resume
      style: link
  has_social: true
  social_links:
    - label: GitHub
      url: 'https://github.com/bhimar'
      style: icon
      icon_class: github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/rehaanbhimani'
      style: icon
      icon_class: linkedin
      new_window: true
    - label: Mail
      url: 'mailto:rehaan.bhimani@gmail.com'
      style: icon
      icon_class: email
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
