title: Chandni A. Rajesh
url: chandnir2.github.io
baseurl: /portfolio-site
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: yellow
favicon: images/favicon.jpg
header:
  title: Chandni A. Rajesh
  tagline: Environmental Scientist @ Tower Engineering Professionals
  # logo_img: images/logo.svg
  # logo_img_alt: Chandni Logo
  background_img: images/GRNL3072.JPG
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Project Blog
      url: /blog
      style: link
    - label: Resume
      url: /resume
      style: link
  has_social: true
  social_links:
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/chandni-rajesh-37ab81228/'
      style: icon
      icon_class: linkedin
      new_window: true
    - label: Mail
      url: 'mailto:chandnir2@gmail.com'
      style: icon
      icon_class: email
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
